export enum LogStandardGlobalEventNameEnum {
  PROCESS_STARTUP_FAILED = 'PROCESS_STARTUP_FAILED',
  USE_CASE_EXECUTION_FAILED = 'USE_CASE_EXECUTION_FAILED',
  USE_CASE_VALIDATION_FAILED = 'USE_CASE_VALIDATION_FAILED',
  SERVICE_REQUEST_FAILED = 'SERVICE_REQUEST_FAILED',
  DATABASE_REQUEST_FAILED = 'DATABASE_REQUEST_FAILED',
  SLOW_HTTP_REQUEST = 'SLOW_HTTP_REQUEST',
}
