name: Information Security Workflow

on:
  workflow_call:
    inputs:
      coverage-path:
        required: true
        type: string
        default: 'coverage-report'

jobs:
  application-security:
    name: actions
    uses: madeiramadeirabr/private_action-information-security-validators/.github/workflows/main.yml@development
    with:
      coverage-path: ${{ github.event.inputs.coverage-path }}